# Generated by Django 5.0.7 on 2024-08-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="activ",
        ),
    ]
